default:
    image: registry.gitlab.com/pvs-hd/ot/diesl

stages:
    - test
    - build
    - docs
    - publish-coverage


unit tests:
    stage: test
    script:
        - nimble test_ci
    artifacts:
        reports:
            junit: result.xml


.test coverage:
    stage: test
    script:
        - nimble install --depsOnly
        - coco --cov="src" --compiler=--hints:off
    artifacts:
        paths:
            - coverage/
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
        - if: '$CI_COMMIT_BRANCH == "develop"'

build demo:
    stage: build
    script:
        - apt-get install -y mingw-w64
        - nimble build
        - nimble build -d:mingw
        - wget https://nim-lang.org/download/dlls.zip
        - unzip dlls.zip
        - cp -r /nim/lib ./stdlib
        - cp -r /root/.nimble/pkgs/fusion-1.0 ./fusion
    artifacts:
        paths:
            - diesl
            - diesl.exe
            - pcre64.dll
            - sqlite3_64.dll
            - diesl/
            - stdlib/
            - fusion/
            - examples/

build docs:
    stage: docs
    script:
        - nimble docgen
    artifacts:
        paths:
            - htmldocs/

pages:
    stage: publish-coverage
    script:
        - mkdir public
        #- mv coverage/ public/coverage
        - mv htmldocs/ public/documentation
    artifacts:
        paths:
            - public/

    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
        - if: '$CI_COMMIT_BRANCH == "develop"'
