
default:
    image: registry.gitlab.com/pvs-hd/ot/diesl

stages:
    - test
    - docs
    - publish-coverage


unit tests:
    stage: test
    script:
        - nimble test_ci
    artifacts:
        reports:
            junit: result.xml


.test coverage:
    stage: test
    script:
        - nimble install --depsOnly
        - coco --cov="src" --compiler=--hints:off
    artifacts:
        paths:
            - coverage/
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
        - if: '$CI_COMMIT_BRANCH == "develop"'

build docs:
    stage: docs
    script:
        - nimble docgen
    artifacts:
        paths:
            - htmldocs/

pages:
    stage: publish-coverage
    script:
        - mkdir public
        #- mv coverage/ public/coverage
        - mv htmldocs/ public/documentation
    artifacts:
        paths:
            - public/

    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
        - if: '$CI_COMMIT_BRANCH == "develop"'
