
default:
    image: registry.gitlab.com/pvs-hd/ot/diesl

stages:
    - test
    - publish-coverage


unit-tests:
    stage: test


test-coverage:
    stage: test
    script:
        - coco  --cov="src" --compiler=--hints:off
    artifacts:
        paths:
            - coverage/
    rules:
        if: '$CI_COMMIT_BRANCH == "master"'
        if: '$CI_COMMIT_BRANCH == "develop"'

pages:
    stage: publish-coverage
    script:
        - cp -r coverage/ public/
    artifacts:
        paths:
            - public/

    rules:
        if: '$CI_COMMIT_BRANCH == "master"'
        if: '$CI_COMMIT_BRANCH == "develop"'
